services:
  - type: web
    name: journal-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: TOGETHER_API_KEY
        value: your_key_here
      - key: MONGO_URI
        value: your_uri_here
    rootDir: backend
